import { useEffect, useState } from "react";
import { Activity, CheckCircle2, CircleX, Sigma } from "lucide-react";
import { ProbeRail, type LayerId } from "../components/ProbeRail";
import { runProbes, type ProbeResult } from "../inference/browserRuntime";

const winner = (scores: number[]) => scores.indexOf(Math.max(...scores));
const carry = (value: number) => value === 1 ? "carry" : "no carry";
type ProbeOutput = { name: string; value: string; expected: string; tone: "digit" | "carry" | "tens"; help: string };

function ProbeOutputNode({ output }: { output: ProbeOutput }) {
  const matches = output.value === output.expected;
  const [showInfo, setShowInfo] = useState(false);
  return <div className={`probe-branch tone-${output.tone}`}><span className="branch-line" aria-hidden="true">→</span><div className="probe-node"><span>{output.name}</span><small>input [128 × 1]</small><button type="button" className="help-button probe-help-button" aria-label={`About ${output.name}`} aria-expanded={showInfo} onClick={() => setShowInfo(!showInfo)}>?</button>{showInfo && <article className="help-popover probe-popover"><strong>{output.name}</strong><p>{output.help}</p><p>A linear classifier was fit on 10,000 independent examples for 100 epochs with AdamW; held-out performance used 5,000 different examples. The probe has 10 output classes for a digit or 2 for a carry. Its displayed prediction is the highest-softmax-probability class.</p></article>}</div><span className="branch-arrow" aria-hidden="true">→</span><div className="probe-result"><strong>{output.value}</strong>{matches ? <CheckCircle2 className="result-good" size={19} aria-label="Matches arithmetic target" /> : <CircleX className="result-bad" size={19} aria-label="Does not match arithmetic target" />}<small>expected {output.expected}</small></div></div>;
}

export function App() {
  const [left, setLeft] = useState("247"), [right, setRight] = useState("586"), [result, setResult] = useState<ProbeResult | null>(null), [error, setError] = useState<string | null>(null), [loading, setLoading] = useState(false), [layer, setLayer] = useState<LayerId>("l0post");
  useEffect(() => { const timer = window.setTimeout(async () => { setLoading(true); try { setResult(await runProbes(Number(left), Number(right))); setError(null); } catch (caught) { setResult(null); setError(caught instanceof Error ? caught.message : "Could not run the probes."); } setLoading(false); }, 250); return () => window.clearTimeout(timer); }, [left, right]);
  const sum = result ? result.left + result.right : null;
  const unitsDigit = result ? winner(result.firstDigitScores) : 0, unitsCarry = result ? winner(result.carryScores) : 0, tensDigit = result ? winner(result.secondDigitScores) : 0, carryIn = result ? winner(result.secondCarryInScores) : 0, tensCarry = result ? winner(result.secondCarryOutScores) : 0;
  const expectedUnits = result ? (result.left + result.right) % 10 : 0, expectedCarryIn = result ? Number(result.left % 10 + result.right % 10 >= 10) : 0, expectedTens = result ? Math.floor((result.left + result.right) / 10) % 10 : 0, expectedTensCarry = result ? Number(Math.floor((result.left + result.right) / 10) >= 10) : 0, expectedHundreds = result ? Math.floor((result.left + result.right) / 100) % 10 : 0, expectedHundredsCarry = result ? Number(Math.floor((result.left + result.right) / 1000) >= 1) : 0;
  const layer0Outputs: ProbeOutput[] = [{ name: "Units digit probe", value: String(unitsDigit), expected: String(expectedUnits), tone: "digit", help: "Reads the layer-0 post residual at the = token and predicts (units-left + units-right) mod 10." }, { name: "Units carry-out probe", value: carry(unitsCarry), expected: carry(expectedCarryIn), tone: "carry", help: "Reads the same layer-0 post residual and predicts whether the units-column sum is at least 10." }];
  const tensOutputs: ProbeOutput[] = [{ name: "Tens digit probe", value: String(tensDigit), expected: String(expectedTens), tone: "tens", help: "Reads layer-1 post after the correct units digit is teacher-forced, then predicts (tens-left + tens-right + units carry-in) mod 10." }, { name: "Units carry-in probe", value: carry(carryIn), expected: carry(expectedCarryIn), tone: "carry", help: "Reads the same layer-1 post residual and predicts whether the units column sent a carry into tens." }, { name: "Tens carry-out probe", value: carry(tensCarry), expected: carry(expectedTensCarry), tone: "carry", help: "Reads the same layer-1 post residual and predicts whether the completed tens column sends a carry into hundreds." }];
  const hundredsOutputs: ProbeOutput[] = [{ name: "Hundreds digit probe", value: String(result ? winner(result.thirdDigitScores) : 0), expected: String(expectedHundreds), tone: "tens", help: "Reads layer-1 post after the correct units and tens digits are teacher-forced, then predicts (hundreds-left + hundreds-right + tens carry-in) mod 10." }, { name: "Tens carry-in probe", value: carry(result ? winner(result.thirdCarryInScores) : 0), expected: carry(expectedTensCarry), tone: "carry", help: "Reads that later layer-1 post residual and predicts whether the tens column sent a carry into hundreds." }, { name: "Hundreds carry-out probe", value: carry(result ? winner(result.thirdCarryOutScores) : 0), expected: carry(expectedHundredsCarry), tone: "carry", help: "Reads that later layer-1 post residual and predicts whether the hundreds column overflows into the final answer digit." }];
  return <main className="app-shell sketch-shell"><header className="app-header"><div className="brand-block"><div className="brand-mark"><Sigma size={26} /></div><div><h1>Addition-GPT</h1><p>Probe Toy</p></div></div><div className="addition-form"><label>Three-digit addition</label><div className="number-inputs"><input aria-label="First addend" value={left} inputMode="numeric" onChange={(event) => setLeft(event.target.value.replace(/\D/g, "").slice(0, 3))} /><span>+</span><input aria-label="Second addend" value={right} inputMode="numeric" onChange={(event) => setRight(event.target.value.replace(/\D/g, "").slice(0, 3))} /><span>=</span><output>{sum ?? "—"}</output></div>{error && <p className="input-error">{error}</p>}</div></header>
    {loading && <p className="runtime-loading">Running probes…</p>}{result && <><div className="runtime-pill"><Activity size={16} /> Browser ONNX runtime</div><ProbeRail active={layer} onSelect={setLayer} prompt={`${result.left} + ${result.right}`} /><section className="flow-diagram"><div className="probe-source"><span className="source-arrow" aria-hidden="true">↓</span><p>{layer === "l0post" ? "Linear probes from the layer 0 post residual at =" : "Layer 1 post: two answer positions"}</p></div>{layer === "l0post" ? <div className="probe-outputs">{layer0Outputs.map((output) => <ProbeOutputNode key={output.name} output={output} />)}</div> : <div className="step-columns"><section className="step-column"><h3>Tens step</h3><p>after units {expectedUnits}</p><div className="probe-outputs">{tensOutputs.map((output) => <ProbeOutputNode key={output.name} output={output} />)}</div></section><section className="step-column"><h3>Hundreds step</h3><p>after units {expectedUnits} and tens {expectedTens}</p><div className="probe-outputs">{hundredsOutputs.map((output) => <ProbeOutputNode key={output.name} output={output} />)}</div></section></div>}</section></>}</main>;
}
